; number of active and inactive substances
9             20
        ; active substances
1            'ASWTOT' ;arseen totaal
2            'CUWTOT' ;koper totaal
3            'NIWTOT' ;nikkel totaal
4            'PBWTOT' ;lood totaal
5            'POCW' ;POC in water
6            'AOCW' ;Algen Koolstof
7            'DOCW' ;Opgelost organisch C waterkolom
8            'SSW' ;zwevende stof water
9            'ZNWTOT' ;zink totaal
        ; passive substances
10            'ASREDT' ;arseen totaal gereduceerde laag
11            'ASSTOT' ;arseen totaal aerobe laag
12            'ASSUBT' ;arseen totaal in onderlaag
13            'CUREDT' ;koper totaal gereduceerde laag
14            'CUSTOT' ;koper totaal aerobe laag
15            'CUSUBT' ;koper totaal in onderlaag
16            'NIREDT' ;nikkel totaal gereduceerde laag
17            'NISTOT' ;nikkel totaal aerobe laag
18            'NISUBT' ;nikkel totaal in onderlaag
19            'PBREDT' ;lood totaal gereduceerde laag
20            'PBSTOT' ;lood totaal aerobe laag
21            'PBSUBT' ;lood totaal in onderlaag
22            'DOCB' ;Opgelost orgamisch C toplaag
23            'DOCSUB' ;Opgelost orgamisch C sediment onderlaag
24            'POCB' ;POC conc. in sediment
25            'POCSUB' ;opgelost POC in onderlaag
26            'S' ;TOTAAL S
27            'ZNREDT' ;zink totaal gereduceerde laag
28            'ZNSTOT' ;zink totaal aerobe laag
29            'ZNSUBT' ;zink totaal in onderlaag